[project]
name = "eda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anja Scherwall", email = "anjagutt@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = ["ipykernel", "pandas", "duckdb"]

[project.scripts]
eda = "eda:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
